# Generated by Django 5.2.17 on 2026-08-27 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0003_documentsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('original_name', models.CharField(max_length=500)),
                ('normalized_name', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(default='reported', max_length=16)),
                ('attributes', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=500)),
                ('quote', models.TextField()),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_references', to='papers.documentblock')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='extraction.extractedentity')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('prompt_version', models.CharField(default='method_extraction_v1', max_length=64)),
                ('schema_version', models.CharField(default='v1', max_length=32)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='papers.paper')),
            ],
        ),
        migrations.AddField(
            model_name='extractedentity',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='extraction.extractionrun'),
        ),
    ]
